# Read the Docs Configuration file
# See https://docs.readthedocs.io/en/stable/config-file/v2.html for details

# Version is required
version: 2

# Set the version of Python and other tools you might need
build:
  os: ubuntu-22.04
  tools:
    python: '3'

# Build documentation in the docs/ directory with Sphinx
sphinx:
  configuration: doc/conf.py

python:
  install:
    - requirements: requirements_docs.txt
